### ISSUE TITLE
Minor UI glitches + suggestions

### ISSUE THREAD

**Issue by stpnwf** [witalihirsch/Mono-firefox-theme#11]
## UI Glitches

I experience those with the unmodified latest release (0.4) in both Firefox (108.0.1) and Librewolf (107.0.1), except in one occasion (details below).

<details>
    <summary>1. Close multiple tabs issue.</summary>
<img src="https://user-images.githubusercontent.com/81482539/209739571-d56e774e-35a9-4591-8d44-56c01e9cd9cd.png">
</details>

<details>
    <summary>2. Wrong search bar height and sidebar icon color.</summary>

I think the black icon colors are also present in the **Bookmarks sidebar**

<img src="https://user-images.githubusercontent.com/81482539/209740497-c9a348f9-77bf-4e31-aa37-d36a336ecf58.png">
</details>

<details>
    <summary>3. Wrong favorite icon color and pin to Overflow Menu artifact.</summary>
<video src="https://user-images.githubusercontent.com/81482539/209743465-16bfb83c-c3b6-4bad-8954-4dceeafd3544.webm" width="500">
</details>

<details>
    <summary>4. Protection setting indentation and weird lock icon behavior.</summary>

Weirdly the lock icon thing only happens in Firefox 108.0.1 and **not** in Librewolf 107.0.1 (both the latest versions available at Flathub)

<video src="https://user-images.githubusercontent.com/81482539/209740886-f0fe50ca-2837-4981-b62d-4607fb277459.webm" width="580">
</details>

 ## Suggestion

As I mentioned in the other issue. I would suggest that the option to not utilize the custom titlebar icons be made easier. I reckon many people will start using [Gradience](https://github.com/GradienceTeam/Gradience) + [adw-gtk3](https://github.com/lassekongo83/adw-gtk3) from here on and a lot of those would love to - like myself - tweak your theme to fit their Gradience theme; and while the purpose of this Firefox theme is to fit the Mono GTK theme, I personally think it would be awesome, and a very helpful thing to be added. Just and idea though :)

Would also love to see the [latest Adwaita symbolic icons](https://github.com/GNOME/adwaita-icon-theme/blob/master/src/symbolic/core.svg) added eventually.

**Comment by witalihirsch** [comment]
1.
![image](https://user-images.githubusercontent.com/73841541/209787556-aef5648e-4abc-4f59-b321-c5d302784645.png)

2. 
![image](https://user-images.githubusercontent.com/73841541/209788988-a8f0b3ac-7375-4908-9bf4-895297a1c898.png)
![image](https://user-images.githubusercontent.com/73841541/209789022-a73994f1-198d-4994-b982-5b4c8e575bbb.png)


3.
![image](https://user-images.githubusercontent.com/73841541/209788272-f3ed93f9-54f3-419d-9f67-391cd7a2eec6.png)

4.
![image](https://user-images.githubusercontent.com/73841541/209788517-d1c2b3f4-33d1-4742-856c-66f8138d5ff4.png)

thanks for the feedback and suggestions, I'll definitely think about it :)

**Comment by stpnwf** [comment]
Awesome, thank you! On my end the latest update fixed all issues except the Pin to Overflow Menu artifact
