### ISSUE TITLE
Canvas extraction permission and notifications icon are misaligned in the URL bar

### ISSUE THREAD

**Issue by xfzv** [witalihirsch/Mono-firefox-theme#13]
Thanks for sharing this theme, looks really good! 

A minor issue I've just noticed, the canvas extraction permission and notifications icons in the URL bar are misaligned:

![image](https://user-images.githubusercontent.com/78810647/212054479-a913a8fe-14bf-42ba-9359-4714e2e6ab9d.png)

- Gentoo / Arch Linux
- Firefox 108.0.2

**Comment by witalihirsch** [comment]
Thanks for the feedback, I'll check it later

**Comment by witalihirsch** [comment]
should be fixed now, check
