### ISSUE TITLE
Extensions icon changed after updating to Firefox 109.0

### ISSUE THREAD

**Issue by xfzv** [witalihirsch/Mono-firefox-theme#14]
- With Firefox 108.0.2:
![image](https://user-images.githubusercontent.com/78810647/212943002-e7b9eab6-59c4-46e2-a125-f234945f6f1d.png)

- After updating to Firefox 109.0:
![image](https://user-images.githubusercontent.com/78810647/212943094-708cc325-cc73-41f1-886a-7e4f4c29890b.png)

Probably because of the new [extensions button](https://support.mozilla.org/en-US/kb/unified-extensions)?

**Comment by witalihirsch** [comment]
and what's the problem? I didn't quite realize

**Comment by witalihirsch** [comment]
ah, I realized, icon doesn't match

**Comment by witalihirsch** [comment]
fixed, extensions icon changed
