### ISSUE TITLE
Firefox private tab unreadable text

### ISSUE THREAD

**Issue by VoQZHD** [witalihirsch/Mono-firefox-theme#4]
Name 	Firefox
Version 	107.0
Build ID 	20221122201151
Distribution ID 	fedora
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
OS 	Linux 6.0.9-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 16 17:36:22 UTC 2022
OS Theme 	MonoThemeDark / Adwaita

![image](https://user-images.githubusercontent.com/45748775/204083777-e095b925-a275-4f86-85c4-4cef0e579d0a.png)
 
![image](https://user-images.githubusercontent.com/45748775/204083798-a9f443e4-147a-4b76-ae9f-36fcc8f492e2.png)

**Comment by witalihirsch** [comment]
are you using the latest version? i fixed this problem recently
![image](https://user-images.githubusercontent.com/73841541/204474477-509e66d8-1273-4587-886a-6334f4e0dfff.png)

**Comment by VoQZHD** [comment]
_I might be not_
