### ISSUE TITLE
Extension icons disproportionate to other icons in toolbar

### ISSUE THREAD

**Issue by arihans** [witalihirsch/Mono-firefox-theme#7]
## Firefox
- Version - 108.0

## Screenshot
![Screenshot from 2022-12-19 15-38-30](https://user-images.githubusercontent.com/39364391/208404500-766379be-6c60-4a87-aac9-56d459bd1007.png)

### Normal icons -
![Screenshot from 2022-12-19 15-56-14](https://user-images.githubusercontent.com/39364391/208404688-02647455-b5c8-4cd1-b8b9-8208189f5184.png)

**Comment by witalihirsch** [comment]
fixed in the last commit

**Comment by arihans** [comment]
Ok Thanks :D

**Comment by arihans** [comment]
Ok Thanks :D
