### ISSUE TITLE
White outline border around active tab

### ISSUE THREAD

**Issue by arihans** [witalihirsch/Mono-firefox-theme#8]
## Firefox
- Version - 108.0

## Screenshot
![Screenshot from 2022-12-19 19-41-49](https://user-images.githubusercontent.com/39364391/208445299-4057d57d-e198-439e-9ac4-0a34d010e0a5.png)

## Solution
```
#navigator-toolbox {
--lwt-tabs-border-color: transparent !important; }
#tabbrowser-tabs {
--lwt-tab-line-color: transparent !important; }
```

**Comment by witalihirsch** [comment]
thanks, i added your part of the code
