### ISSUE TITLE
How to use with stock windows buttons?

### ISSUE THREAD

**Issue by stpnwf** [witalihirsch/Mono-firefox-theme#9]
Hi, how can I make it so the stock title buttons are used instead of the Mono ones?
I was able to edit the colors of the theme so it fits with the theme I am using, but I would like to use the my theme's default windows icons rather than the mono theme ones.

**Comment by witalihirsch** [comment]
Go to `mono-firefox-theme` > `theme` > `parts` > `csd.css` and edit in this file

**Comment by iAutistic** [comment]
how can i change theme to be like this ?
![image](https://user-images.githubusercontent.com/68719131/209598589-34614730-7ed2-415c-bb71-32d3605d5712.png)
![image](https://user-images.githubusercontent.com/68719131/209598620-0e3ba118-7e33-442e-bf32-f196e7630e77.png)
![image](https://user-images.githubusercontent.com/68719131/209598649-d7dc8ced-f4b3-4a0a-8a53-85f694f02e84.png)
![image](https://user-images.githubusercontent.com/68719131/209598636-86633362-b728-480a-86f3-b80cbe804061.png)

**Comment by stpnwf** [comment]
Thanks @witalihirsch, I was able to eventually get it to work. I had to make changes to `csd.css` as well as `icons.css` so as to prevent the close/maximize/minimize icons from showing up. 

May I suggest that the windows buttons be done separately in a `titlebutons.css`, that way users can just remove it if they wish to use just their default gtk theme's title buttons. Personally I am using Gradience and I am able to tweak the title bars to my liking right from there.

@iAutistic I suspect you can edit the `icons.css` files as well as `csd.css` file to accomplish that. You need to know CSS to accomplish that. If you are up for it, [WhiteSur](https://github.com/vinceliuice/WhiteSur-gtk-theme) may have the close, maximize, and minimize icons you will need.

I have [accomplished this](https://imgur.com/a/Mbh0pge) though with just [Gradience](https://github.com/GradienceTeam/Gradience) and [adw-gk3](https://github.com/lassekongo83/adw-gtk3). By tweaking the Rose Pine Template colors.

The downside to this is that it does not have the close, maximize, and minimize icons show up when you hover he button. Which I am fine with. You could prob tweak it further to get the icons to show up on hover and then just do the same as I did to get the system's default buttons to show up...
